### PR TITLE
fix: Revert type=module change

### PR DESCRIPTION
**Pull request by timphillips**
The changes in https://github.com/unravelin/ravelinjs/pull/341 introduced an issue with importing RavelinJS via the npm package (reported in [this](https://ravelin.slack.com/archives/CMVJZHPUG/p1687183550330789) internal Slack thread). 

The default import (e.g. `import Ravelin from 'ravelinjs/core'`) now returns `undefined` instead of the expected Ravelin constructor function. Ravelin is instead being initialised as a global variable.

The format of the bundles published in v1.8.0 are identical to v1.7.1. It appears that the `"type": "module"` change in `package.json` impacts how the package is imported in build systems. This reverts the change until we determine the magical combination of config options required for a proper fix. 

https://github.com/unravelin/ravelinjs/pull/344 was also reverted because it depends on https://github.com/unravelin/ravelinjs/pull/341 (though I've preserved the change to target IE11 in tests).

### CODE REVIEW

**Review by ericmatteucci — APPROVED** [review]
LGTM! Thanks for this

**Review by talon266 — APPROVED** [review]
LGTM
I think we need to determine what's a module and what's commonjs and perhaps split it into 2 projects?
https://nodejs.org/api/packages.html#type

**Comment by icio** [comment]
Bah, apologies for this. I think the part I forgot to update was: https://github.com/unravelin/ravelinjs/blob/177bcbff22238545f1049a3b0c9c3d9423f1b226/rollup.config.js#L65-L69

This should probably be:

```diff
   file: 'dist/' + basename(bundle),
-  format: 'umd',
-  name: 'Ravelin',
-  esModule: false,
-  exports: 'default',
+  format: 'es',
```

However, it's potentially going to be a nuisance getting `require` and `import` to work in a backwards-compatible manner when switching to modules. `require` isn't technically supported by ESModules. The switch to ESModules could just be part of the `v2` branch in #345 so that we don't need to worry about supporting both styles.

**Comment by icio** [comment]
Some good links here on the matter: https://deno.com/blog/commonjs-is-hurting-javascript.

Anyway, peace :v: Hope to see you all soon.

**Pull request merged**
