### PR TITLE
Use debian node:10 image.

### PR DESCRIPTION
**Pull request by icio**
browserstack-local is segfaulting on alpine: https://github.com/browserstack/browserstack-local-nodejs/issues/137

### CODE REVIEW

**Review by adamroyjones — APPROVED** [review]
👑

We can look at moving to the current LTS (18) soon.

**Comment by icio** [comment]
Yes, soon... https://github.com/unravelin/ravelinjs/pull/165

**Comment by adamroyjones** [comment]
The CI pipeline is failing. 😞

**Comment by icio** [comment]
I've re-run. The failures are just browserstack failing to create some sessions intermittently. I think we're fine to merge.

**Pull request merged**
